use serde::Serialize;
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
pub struct Preset {
    pub platform: &'static str,
    pub aspect: &'static str,
    pub width: u32,
    pub height: u32,
    pub fps: u32,
}

pub const PRESETS: &[Preset] = &[
    Preset {
        platform: "Instagram",
        aspect: "Horizontal video (16:9)",
        width: 1920,
        height: 1080,
        fps: 30,
    },
    Preset {
        platform: "Instagram",
        aspect: "Square (1:1)",
        width: 1080,
        height: 1080,
        fps: 30,
    },
    Preset {
        platform: "Instagram",
        aspect: "4:5",
        width: 1080,
        height: 1350,
        fps: 30,
    },
    Preset {
        platform: "Instagram",
        aspect: "Vertical video (9:16)",
        width: 1080,
        height: 1920,
        fps: 30,
    },
    Preset {
        platform: "TikTok",
        aspect: "Vertical video (9:16)",
        width: 1080,
        height: 1920,
        fps: 30,
    },
    Preset {
        platform: "TikTok",
        aspect: "Vertical video (9:16)",
        width: 720,
        height: 1280,
        fps: 30,
    },
    Preset {
        platform: "Facebook",
        aspect: "Horizontal video (16:9)",
        width: 1280,
        height: 720,
        fps: 30,
    },
    Preset {
        platform: "Facebook",
        aspect: "Square (1:1)",
        width: 1080,
        height: 1080,
        fps: 30,
    },
    Preset {
        platform: "Facebook",
        aspect: "Vertical video (9:16)",
        width: 720,
        height: 1280,
        fps: 30,
    },
    Preset {
        platform: "Facebook",
        aspect: "Vertical video (9:16)",
        width: 1080,
        height: 1920,
        fps: 30,
    },
    Preset {
        platform: "Facebook",
        aspect: "4:5",
        width: 1080,
        height: 1350,
        fps: 30,
    },
    Preset {
        platform: "Twitter / X",
        aspect: "Horizontal video (16:9)",
        width: 1280,
        height: 720,
        fps: 30,
    },
    Preset {
        platform: "Twitter / X",
        aspect: "Square (1:1)",
        width: 720,
        height: 720,
        fps: 30,
    },
    Preset {
        platform: "Twitter / X",
        aspect: "Vertical video (9:16)",
        width: 720,
        height: 1280,
        fps: 30,
    },
    Preset {
        platform: "YouTube",
        aspect: "Horizontal video (16:9)",
        width: 1920,
        height: 1080,
        fps: 30,
    },
    Preset {
        platform: "YouTube",
        aspect: "Vertical video (9:16)",
        width: 1080,
        height: 1920,
        fps: 30,
    },
    Preset {
        platform: "YouTube",
        aspect: "Square (1:1)",
        width: 1080,
        height: 1080,
        fps: 30,
    },
    Preset {
        platform: "YouTube",
        aspect: "4:3",
        width: 1440,
        height: 1080,
        fps: 30,
    },
    Preset {
        platform: "LinkedIn",
        aspect: "Horizontal video (16:9)",
        width: 1920,
        height: 1080,
        fps: 30,
    },
    Preset {
        platform: "LinkedIn",
        aspect: "Square (1:1)",
        width: 1080,
        height: 1080,
        fps: 30,
    },
    Preset {
        platform: "Snapchat",
        aspect: "Vertical video (9:16)",
        width: 1080,
        height: 1920,
        fps: 30,
    },
    Preset {
        platform: "Pinterest",
        aspect: "Vertical video (9:16)",
        width: 1080,
        height: 1920,
        fps: 30,
    },
    Preset {
        platform: "Generic",
        aspect: "Horizontal video (16:9)",
        width: 1920,
        height: 1080,
        fps: 30,
    },
    Preset {
        platform: "Generic",
        aspect: "Vertical video (9:16)",
        width: 1080,
        height: 1920,
        fps: 30,
    },
    Preset {
        platform: "Generic",
        aspect: "Square (1:1)",
        width: 1080,
        height: 1080,
        fps: 30,
    },
    Preset {
        platform: "Generic",
        aspect: "4:3",
        width: 1440,
        height: 1080,
        fps: 30,
    },
    Preset {
        platform: "Generic",
        aspect: "4:5",
        width: 1080,
        height: 1350,
        fps: 30,
    },
];
